import type { CommerceCoupon } from '../model/coupon-types';
import type {
  CommerceCouponSubscriptionTemplate,
  CouponAuditEvent
} from '../model/coupon-template-types';
import { getCouponPolicyNotes } from '../model/coupon-form-schema';
import {
  getCouponTemplatePolicyNotes,
  resolveCouponTemplateCategoryNames,
  resolveCouponTemplateProductNames,
  resolveCouponTemplateShoppingGradeNames
} from '../model/coupon-template-form-schema';

const messageGroupNameMap: Record<string, string> = {
  'GRP-001': '활성 학습자',
  'GRP-002': '이탈 예정 강사',
  'GRP-003': 'VIP 고객',
  'GRP-004': '운영 공지 구독자'
};

const messageTemplateNameMap: Record<string, string> = {
  'MAIL-AUTO-001': '가입 환영 메일',
  'MAIL-AUTO-002': '결제 실패 리마인드',
  'MAIL-MAN-001': '월간 뉴스레터',
  'MAIL-MAN-002': 'VIP 행사 초대 메일',
  'PUSH-AUTO-001': '댓글 답변 알림',
  'PUSH-AUTO-002': '정기 결제 예정 알림',
  'PUSH-MAN-001': '장애 공지 푸시',
  'PUSH-MAN-002': '주말 캠페인 안내'
};

const crmCampaignNameMap: Record<string, string> = {
  'CRM-CART-001': '장바구니 상품 구매 유도',
  'CRM-WELCOME-001': '자동 발행 쿠폰 안내',
  'CRM-EXPIRE-001': '쿠폰 기간 만료 안내',
  'CRM-MANUAL-001': '지정 발행 쿠폰 알림'
};

const eventNameMap: Record<string, string> = {
  'EVT-COUPON-001': '봄맞이 쿠폰팩 랜딩',
  'EVT-COUPON-002': '장바구니 CRM 리텐션',
  'EVT-COUPON-003': '웰컴 혜택 프로모션'
};

function createDownloadUrl(couponId: string): string {
  return `https://topik.ai/coupons/${couponId.toLowerCase()}`;
}

function resolveGroupNames(groupIds: string[]): string[] {
  return groupIds.map((groupId) => messageGroupNameMap[groupId] ?? '').filter(Boolean);
}

function resolveTemplateName(templateId: string): string {
  return messageTemplateNameMap[templateId] ?? '';
}

function resolveCrmCampaignName(campaignId: string): string {
  return crmCampaignNameMap[campaignId] ?? '';
}

function resolveEventName(eventId: string): string {
  return eventNameMap[eventId] ?? '';
}

function createSeedCoupon(seed: CommerceCoupon): CommerceCoupon {
  return seed;
}

const mockCoupons: CommerceCoupon[] = [
  createSeedCoupon({
    id: "CPN-0001",
    couponName: "채널 친구 추가 시크릿 쿠폰",
    couponKind: "customerDownload",
    couponStatus: "진행 중",
    issueState: "정상",
    issueTargetType: "allMembers",
    targetGroupIds: [],
    targetGroupNames: [],
    targetUserIds: [],
    autoIssueTriggerType: null,
    codeGenerationMode: null,
    couponCode: "",
    codeCount: null,
    audience: null,
    benefitType: "amountDiscount",
    benefitValue: 3000,
    minOrderAmount: 10000,
    maxDiscountAmount: null,
    applicableScope: "allProducts",
    isStackable: false,
    isSecretCoupon: true,
    issueLimitMode: "limited",
    issueLimit: 3000,
    downloadLimitMode: "limited",
    downloadLimit: 3000,
    usageLimitMode: "limited",
    usageLimit: 1,
    validityMode: "afterIssued",
    validFrom: "2026-03-01",
    validUntil: "2026-05-31",
    expireAfterDays: 14,
    linkedMessageTemplateId: "PUSH-MAN-002",
    linkedMessageTemplateName: resolveTemplateName("PUSH-MAN-002"),
    linkedCrmCampaignId: "",
    linkedCrmCampaignName: "",
    linkedEventId: "EVT-COUPON-001",
    linkedEventName: resolveEventName("EVT-COUPON-001"),
    downloadUrl: createDownloadUrl("CPN-0001"),
    issueCount: 1280,
    downloadCount: 984,
    useCount: 462,
    lastIssuedAt: "2026-03-24 18:10",
    lastDownloadedAt: "2026-03-24 18:20",
    lastUsedAt: "2026-03-24 19:40",
    policyNotes: getCouponPolicyNotes("customerDownload", null),
    adminMemo: "웰컴 메시지 CTA와 연결한 시크릿 쿠폰입니다.",
    createdAt: "2026-03-01 09:10",
    updatedAt: "2026-03-24 19:40",
    updatedBy: "admin_park",
    issueAlert: {
      enabled: true,
      channel: "alimtalk",
      templateId: "PUSH-MAN-002",
      templateName: resolveTemplateName("PUSH-MAN-002"),
      timingLabel: "다운로드 즉시",
    },
    expireAlert: {
      enabled: false,
      channel: "webPush",
      templateId: "",
      templateName: "",
      timingLabel: "사용 안 함",
    },
  }),
  createSeedCoupon({
    id: "CPN-0002",
    couponName: "웰컴 쿠폰 10%",
    couponKind: "autoIssue",
    couponStatus: "진행 중",
    issueState: "정상",
    issueTargetType: null,
    targetGroupIds: [],
    targetGroupNames: [],
    targetUserIds: [],
    autoIssueTriggerType: "firstSignup",
    codeGenerationMode: null,
    couponCode: "",
    codeCount: null,
    audience: null,
    benefitType: "rateDiscount",
    benefitValue: 10,
    minOrderAmount: 15000,
    maxDiscountAmount: 10000,
    applicableScope: "allProducts",
    isStackable: false,
    isSecretCoupon: false,
    issueLimitMode: "unlimited",
    issueLimit: null,
    downloadLimitMode: "unlimited",
    downloadLimit: null,
    usageLimitMode: "limited",
    usageLimit: 1,
    validityMode: "afterIssued",
    validFrom: "2026-03-01",
    validUntil: "2026-12-31",
    expireAfterDays: 30,
    linkedMessageTemplateId: "MAIL-AUTO-001",
    linkedMessageTemplateName: resolveTemplateName("MAIL-AUTO-001"),
    linkedCrmCampaignId: "CRM-WELCOME-001",
    linkedCrmCampaignName: resolveCrmCampaignName("CRM-WELCOME-001"),
    linkedEventId: "EVT-COUPON-003",
    linkedEventName: resolveEventName("EVT-COUPON-003"),
    downloadUrl: "",
    issueCount: 820,
    downloadCount: 0,
    useCount: 314,
    lastIssuedAt: "2026-03-25 09:00",
    lastDownloadedAt: "",
    lastUsedAt: "2026-03-25 11:15",
    policyNotes: getCouponPolicyNotes("autoIssue", "firstSignup"),
    adminMemo: "첫 회원가입 자동 발행과 CRM 안내를 함께 검수합니다.",
    createdAt: "2026-03-02 11:00",
    updatedAt: "2026-03-25 11:15",
    updatedBy: "admin_kim",
    issueAlert: {
      enabled: true,
      channel: "alimtalk",
      templateId: "MAIL-AUTO-001",
      templateName: resolveTemplateName("MAIL-AUTO-001"),
      timingLabel: "발급 즉시",
    },
    expireAlert: {
      enabled: true,
      channel: "alimtalk",
      templateId: "MAIL-AUTO-002",
      templateName: resolveTemplateName("MAIL-AUTO-002"),
      timingLabel: "만료 1일 전",
    },
  }),
  createSeedCoupon({
    id: "CPN-0003",
    couponName: "생일 축하 쿠폰",
    couponKind: "autoIssue",
    couponStatus: "진행 중",
    issueState: "발행 중지",
    issueTargetType: null,
    targetGroupIds: [],
    targetGroupNames: [],
    targetUserIds: [],
    autoIssueTriggerType: "birthday",
    codeGenerationMode: null,
    couponCode: "",
    codeCount: null,
    audience: null,
    benefitType: "amountDiscount",
    benefitValue: 5000,
    minOrderAmount: 30000,
    maxDiscountAmount: null,
    applicableScope: "allProducts",
    isStackable: false,
    isSecretCoupon: false,
    issueLimitMode: "unlimited",
    issueLimit: null,
    downloadLimitMode: "unlimited",
    downloadLimit: null,
    usageLimitMode: "limited",
    usageLimit: 1,
    validityMode: "afterIssued",
    validFrom: "2026-02-01",
    validUntil: "2026-12-31",
    expireAfterDays: 7,
    linkedMessageTemplateId: "",
    linkedMessageTemplateName: "",
    linkedCrmCampaignId: "",
    linkedCrmCampaignName: "",
    linkedEventId: "",
    linkedEventName: "",
    downloadUrl: "",
    issueCount: 105,
    downloadCount: 0,
    useCount: 24,
    lastIssuedAt: "2026-03-10 00:10",
    lastDownloadedAt: "",
    lastUsedAt: "2026-03-12 14:55",
    policyNotes: getCouponPolicyNotes("autoIssue", "birthday"),
    adminMemo:
      "생년월일 누락 회원이 많아 발행 재개 전 데이터 수집 정책 검토가 필요합니다.",
    createdAt: "2026-02-01 09:00",
    updatedAt: "2026-03-18 12:10",
    updatedBy: "admin_lee",
    issueAlert: {
      enabled: false,
      channel: "alimtalk",
      templateId: "",
      templateName: "",
      timingLabel: "사용 안 함",
    },
    expireAlert: {
      enabled: true,
      channel: "webPush",
      templateId: "",
      templateName: "",
      timingLabel: "만료 1일 전",
    },
  }),
  createSeedCoupon({
    id: "CPN-0004",
    couponName: "인플루언서 제휴 코드",
    couponKind: "couponCode",
    couponStatus: "진행 중",
    issueState: "정상",
    issueTargetType: null,
    targetGroupIds: [],
    targetGroupNames: [],
    targetUserIds: [],
    autoIssueTriggerType: null,
    codeGenerationMode: "single",
    couponCode: "TOPIKTEST01",
    codeCount: 1,
    audience: "memberAndGuest",
    benefitType: "amountDiscount",
    benefitValue: 2000,
    minOrderAmount: 15000,
    maxDiscountAmount: null,
    applicableScope: "allProducts",
    isStackable: false,
    isSecretCoupon: false,
    issueLimitMode: "unlimited",
    issueLimit: null,
    downloadLimitMode: "unlimited",
    downloadLimit: null,
    usageLimitMode: "limited",
    usageLimit: 1,
    validityMode: "fixedDate",
    validFrom: "2026-03-20",
    validUntil: "2026-04-20",
    expireAfterDays: null,
    linkedMessageTemplateId: "",
    linkedMessageTemplateName: "",
    linkedCrmCampaignId: "",
    linkedCrmCampaignName: "",
    linkedEventId: "",
    linkedEventName: "",
    downloadUrl: "",
    issueCount: 84,
    downloadCount: 0,
    useCount: 27,
    lastIssuedAt: "",
    lastDownloadedAt: "",
    lastUsedAt: "2026-03-24 20:05",
    policyNotes: getCouponPolicyNotes("couponCode", null),
    adminMemo:
      "제휴 코드 오타 방지를 위해 저장 후 코드 수정은 허용하지 않습니다.",
    createdAt: "2026-03-20 13:00",
    updatedAt: "2026-03-24 20:05",
    updatedBy: "admin_park",
    issueAlert: {
      enabled: false,
      channel: "webPush",
      templateId: "",
      templateName: "",
      timingLabel: "사용 안 함",
    },
    expireAlert: {
      enabled: false,
      channel: "webPush",
      templateId: "",
      templateName: "",
      timingLabel: "사용 안 함",
    },
  }),
  createSeedCoupon({
    id: "CPN-0005",
    couponName: "리텐션 타깃 재방문 쿠폰",
    couponKind: "manualIssue",
    couponStatus: "대기",
    issueState: "정상",
    issueTargetType: "specificGroup",
    targetGroupIds: ["GRP-002"],
    targetGroupNames: resolveGroupNames(["GRP-002"]),
    targetUserIds: [],
    autoIssueTriggerType: null,
    codeGenerationMode: null,
    couponCode: "",
    codeCount: null,
    audience: null,
    benefitType: "amountDiscount",
    benefitValue: 4000,
    minOrderAmount: 20000,
    maxDiscountAmount: null,
    applicableScope: "allProducts",
    isStackable: true,
    isSecretCoupon: false,
    issueLimitMode: "limited",
    issueLimit: 1000,
    downloadLimitMode: "unlimited",
    downloadLimit: null,
    usageLimitMode: "limited",
    usageLimit: 1,
    validityMode: "fixedDate",
    validFrom: "2026-03-28",
    validUntil: "2026-04-05",
    expireAfterDays: null,
    linkedMessageTemplateId: "PUSH-AUTO-001",
    linkedMessageTemplateName: resolveTemplateName("PUSH-AUTO-001"),
    linkedCrmCampaignId: "CRM-MANUAL-001",
    linkedCrmCampaignName: resolveCrmCampaignName("CRM-MANUAL-001"),
    linkedEventId: "EVT-COUPON-002",
    linkedEventName: resolveEventName("EVT-COUPON-002"),
    downloadUrl: "",
    issueCount: 0,
    downloadCount: 0,
    useCount: 0,
    lastIssuedAt: "",
    lastDownloadedAt: "",
    lastUsedAt: "",
    policyNotes: getCouponPolicyNotes("manualIssue", null),
    adminMemo: "최근 구매자 제외 그룹에만 발행 예정입니다.",
    createdAt: "2026-03-24 16:10",
    updatedAt: "2026-03-24 16:10",
    updatedBy: "admin_kim",
    issueAlert: {
      enabled: true,
      channel: "webPush",
      templateId: "",
      templateName: "",
      timingLabel: "발급 즉시",
    },
    expireAlert: {
      enabled: true,
      channel: "alimtalk",
      templateId: "MAIL-AUTO-002",
      templateName: resolveTemplateName("MAIL-AUTO-002"),
      timingLabel: "만료 1일 전",
    },
  }),
  createSeedCoupon({
    id: "CPN-0006",
    couponName: "장바구니 리마인드 쿠폰",
    couponKind: "customerDownload",
    couponStatus: "종료",
    issueState: "정상",
    issueTargetType: "allMembers",
    targetGroupIds: [],
    targetGroupNames: [],
    targetUserIds: [],
    autoIssueTriggerType: null,
    codeGenerationMode: null,
    couponCode: "",
    codeCount: null,
    audience: null,
    benefitType: "amountDiscount",
    benefitValue: 1000,
    minOrderAmount: 5000,
    maxDiscountAmount: null,
    applicableScope: "allProducts",
    isStackable: false,
    isSecretCoupon: true,
    issueLimitMode: "unlimited",
    issueLimit: null,
    downloadLimitMode: "unlimited",
    downloadLimit: null,
    usageLimitMode: "limited",
    usageLimit: 1,
    validityMode: "afterIssued",
    validFrom: "2026-03-01",
    validUntil: "2026-03-20",
    expireAfterDays: 3,
    linkedMessageTemplateId: "PUSH-MAN-001",
    linkedMessageTemplateName: resolveTemplateName("PUSH-MAN-001"),
    linkedCrmCampaignId: "CRM-CART-001",
    linkedCrmCampaignName: resolveCrmCampaignName("CRM-CART-001"),
    linkedEventId: "",
    linkedEventName: "",
    downloadUrl: createDownloadUrl("CPN-0006"),
    issueCount: 620,
    downloadCount: 410,
    useCount: 188,
    lastIssuedAt: "2026-03-19 22:30",
    lastDownloadedAt: "2026-03-20 00:05",
    lastUsedAt: "2026-03-20 11:20",
    policyNotes: getCouponPolicyNotes("customerDownload", null),
    adminMemo: "종료된 쿠폰이지만 운영 복기용으로 기록을 유지합니다.",
    createdAt: "2026-03-01 18:20",
    updatedAt: "2026-03-20 11:20",
    updatedBy: "admin_park",
    issueAlert: {
      enabled: true,
      channel: "alimtalk",
      templateId: "PUSH-MAN-001",
      templateName: resolveTemplateName("PUSH-MAN-001"),
      timingLabel: "발급 즉시",
    },
    expireAlert: {
      enabled: false,
      channel: "webPush",
      templateId: "",
      templateName: "",
      timingLabel: "사용 안 함",
    },
  }),
];

const mockCouponSubscriptionTemplates: CommerceCouponSubscriptionTemplate[] = [
  {
    id: "CPT-0001",
    templateName: "웰컴 회원 정기 쿠폰",
    issueTargetType: "shoppingGrade",
    targetGradeIds: ["SHOP-GRADE-WELCOME"],
    targetGradeNames: resolveCouponTemplateShoppingGradeNames([
      "SHOP-GRADE-WELCOME",
    ]),
    benefitType: "amountDiscount",
    benefitValue: 3000,
    minOrderAmount: 10000,
    maxDiscountAmount: null,
    applicableScope: "allProducts",
    applicableScopeReferenceIds: [],
    applicableScopeReferenceNames: [],
    excludedProductMode: "none",
    excludedProductIds: [],
    excludedProductNames: [],
    isStackable: false,
    issueSchedule: {
      dayOfMonth: 1,
      hour: 7,
      minute: 0,
    },
    usageEndSchedule: {
      dayOfMonth: 28,
      hour: 23,
      minute: 59,
    },
    status: "진행 중",
    issuedCouponCount: 1820,
    lastIssuedAt: "2026-03-01 07:00",
    nextIssuedAt: "2026-04-01 07:00",
    issueAlertEnabled: true,
    expireAlertEnabled: false,
    alertChannel: "webAppPush",
    adminMemo: "웰컴 등급 대상 월별 리텐션 쿠폰입니다.",
    policyNotes: getCouponTemplatePolicyNotes(["SHOP-GRADE-WELCOME"]),
    createdAt: "2026-01-02 10:30",
    updatedAt: "2026-03-24 14:10",
    updatedBy: "admin_kim",
  },
  {
    id: "CPT-0002",
    templateName: "VIP 재구매 유도 쿠폰",
    issueTargetType: "shoppingGrade",
    targetGradeIds: ["SHOP-GRADE-VIP"],
    targetGradeNames: resolveCouponTemplateShoppingGradeNames([
      "SHOP-GRADE-VIP",
    ]),
    benefitType: "rateDiscount",
    benefitValue: 12,
    minOrderAmount: 30000,
    maxDiscountAmount: 15000,
    applicableScope: "specificCategory",
    applicableScopeReferenceIds: ["CAT-TOPIK-READING", "CAT-TOPIK-SPEAKING"],
    applicableScopeReferenceNames: resolveCouponTemplateCategoryNames([
      "CAT-TOPIK-READING",
      "CAT-TOPIK-SPEAKING",
    ]),
    excludedProductMode: "specific",
    excludedProductIds: ["PRD-COURSE-003"],
    excludedProductNames: resolveCouponTemplateProductNames(["PRD-COURSE-003"]),
    isStackable: true,
    issueSchedule: {
      dayOfMonth: 1,
      hour: 7,
      minute: 0,
    },
    usageEndSchedule: {
      dayOfMonth: 21,
      hour: 23,
      minute: 30,
    },
    status: "발행 중지",
    issuedCouponCount: 420,
    lastIssuedAt: "2026-02-01 07:00",
    nextIssuedAt: "2026-04-01 07:00",
    issueAlertEnabled: true,
    expireAlertEnabled: true,
    alertChannel: "webAppPush",
    adminMemo:
      "VIP 등급 전환 프로모션과 겹치지 않도록 3월 발행을 중지했습니다.",
    policyNotes: getCouponTemplatePolicyNotes(["SHOP-GRADE-VIP"]),
    createdAt: "2026-01-10 09:20",
    updatedAt: "2026-03-10 18:05",
    updatedBy: "admin_park",
  },
];

const mockCouponAudits: CouponAuditEvent[] = [
  {
    id: "AL-CPN-0001",
    targetType: "CommerceCouponTemplate",
    targetId: "CPT-0002",
    action: "정기 쿠폰 템플릿 발행 중지",
    reason: "VIP 재구매 유도 쿠폰과 등급 전환 프로모션 중복 검수",
    changedBy: "admin_park",
    createdAt: "2026-03-10 18:05",
  },
];


function cloneCoupon(coupon: CommerceCoupon): CommerceCoupon {
  return {
    ...coupon,
    targetGroupIds: [...coupon.targetGroupIds],
    targetGroupNames: [...coupon.targetGroupNames],
    targetUserIds: [...coupon.targetUserIds],
    applicableScope: coupon.applicableScope,
    issueAlert: { ...coupon.issueAlert },
    expireAlert: { ...coupon.expireAlert }
  };
}

function cloneTemplate(template: CommerceCouponSubscriptionTemplate): CommerceCouponSubscriptionTemplate {
  return {
    ...template,
    targetGradeIds: [...template.targetGradeIds],
    targetGradeNames: [...template.targetGradeNames],
    applicableScopeReferenceIds: [...template.applicableScopeReferenceIds],
    applicableScopeReferenceNames: [...template.applicableScopeReferenceNames],
    excludedProductIds: [...template.excludedProductIds],
    excludedProductNames: [...template.excludedProductNames],
    issueSchedule: { ...template.issueSchedule },
    usageEndSchedule: { ...template.usageEndSchedule },
    policyNotes: [...template.policyNotes]
  };
}

function cloneAudit(audit: CouponAuditEvent): CouponAuditEvent {
  return { ...audit };
}

export function createInitialCoupons(): CommerceCoupon[] {
  return mockCoupons.map(cloneCoupon);
}

export function createInitialCouponSubscriptionTemplates(): CommerceCouponSubscriptionTemplate[] {
  return mockCouponSubscriptionTemplates.map(cloneTemplate);
}

export function createInitialCouponAudits(): CouponAuditEvent[] {
  return mockCouponAudits.map(cloneAudit);
}
