-- Roll back to Supabase's prior direct anon EXECUTE grants.
do $migration$
declare
  function_name text;
  function_signature regprocedure;
  admin_function_names constant text[] := array[
    'admin_add_community_post_memo',
    'admin_add_instructor_note',
    'admin_add_user_memo',
    'admin_adjust_referral_reward',
    'admin_approve_billing_refund',
    'admin_assign_institution_code',
    'admin_cancel_institution_invitation',
    'admin_cancel_notification_dispatch',
    'admin_clear_institution_code',
    'admin_create_institution_code',
    'admin_create_manual_point_adjustment',
    'admin_create_pdf_quota_reset',
    'admin_delete_commerce_coupon',
    'admin_delete_commerce_coupon_template',
    'admin_delete_community_post',
    'admin_delete_institution_code',
    'admin_delete_instructor_note',
    'admin_delete_metadata_item',
    'admin_delete_notification_group',
    'admin_delete_notification_template',
    'admin_delete_operation_faq',
    'admin_delete_operation_faq_curation',
    'admin_delete_operation_notice',
    'admin_delete_operation_policy',
    'admin_delete_user_memo',
    'admin_duplicate_commerce_coupon',
    'admin_end_operation_event',
    'admin_export_users',
    'admin_finalize_invite',
    'admin_get_admin',
    'admin_get_instructor',
    'admin_get_self',
    'admin_get_user_access_logs',
    'admin_get_user_activity',
    'admin_get_user_community_posts',
    'admin_get_user_legal_consents',
    'admin_get_user_payment_history',
    'admin_get_user_payments',
    'admin_get_user_study_events',
    'admin_grant_permissions',
    'admin_has_permission',
    'admin_hide_community_post',
    'admin_hold_commerce_point_expiration',
    'admin_invite_institution_members',
    'admin_list_admin_app_roles',
    'admin_list_admins',
    'admin_list_audit_logs',
    'admin_list_institution_code_members',
    'admin_list_institution_codes',
    'admin_list_institution_invitations',
    'admin_list_instructors',
    'admin_list_referrals',
    'admin_list_user_memos',
    'admin_mark_auth_email_synced',
    'admin_publish_operation_event',
    'admin_publish_operation_policy_version',
    'admin_reject_billing_refund',
    'admin_release_commerce_point_expiration',
    'admin_reorder_metadata_items',
    'admin_resolve_community_report',
    'admin_review_referral_anomaly',
    'admin_revoke_permissions',
    'admin_save_auth_email_template',
    'admin_save_commerce_coupon',
    'admin_save_commerce_coupon_template',
    'admin_save_commerce_point_policy',
    'admin_save_metadata_group',
    'admin_save_metadata_item',
    'admin_save_notification_group',
    'admin_save_notification_template',
    'admin_save_operation_event',
    'admin_save_operation_faq',
    'admin_save_operation_faq_curation',
    'admin_save_operation_notice',
    'admin_save_operation_policy',
    'admin_save_pdf_quota_policy',
    'admin_schedule_operation_event',
    'admin_send_notification',
    'admin_send_terms_change_notification',
    'admin_set_admin_app_role',
    'admin_set_admin_role',
    'admin_set_admin_status',
    'admin_set_commerce_coupon_issue_state',
    'admin_set_commerce_coupon_template_status',
    'admin_set_instructor_status',
    'admin_set_notification_template_status',
    'admin_set_referral_status',
    'admin_set_user_status',
    'admin_show_community_post',
    'admin_toggle_metadata_group_status',
    'admin_toggle_metadata_item_status',
    'admin_toggle_operation_faq_status',
    'admin_toggle_operation_notice_status',
    'admin_toggle_operation_policy_status',
    'admin_update_commerce_point_policy_status',
    'admin_update_institution_code',
    'get_admin_analytics_overview',
    'get_admin_dashboard_stats',
    'get_admin_learning_analytics',
    'get_admin_learning_analytics_filter_options',
    'get_admin_learning_analytics_filtered',
    'get_admin_pdf_quota_policies',
    'get_admin_pdf_quota_policy_history',
    'get_admin_pdf_quota_resets',
    'get_admin_user',
    'get_admin_user_learning_overview',
    'get_admin_users',
    'next_commerce_coupon_id',
    'next_commerce_coupon_template_id',
    'next_commerce_point_ledger_id',
    'next_commerce_point_policy_id',
    'next_commerce_refund_id',
    'next_community_post_admin_note_id',
    'next_community_post_id',
    'next_operation_policy_history_id',
    'next_operation_policy_id',
    'next_system_metadata_group_id',
    'next_system_metadata_item_id',
    'operation_policy_snapshot',
    'respond_institution_invitation',
    'search_admin_pdf_quota_reset_users'
  ];
begin
  foreach function_name in array admin_function_names loop
    for function_signature in
      select p.oid::regprocedure
      from pg_proc as p
      join pg_namespace as n on n.oid = p.pronamespace
      where n.nspname = 'public'
        and p.proname = function_name
    loop
      execute format(
        'grant execute on function %s to anon',
        function_signature
      );
    end loop;
  end loop;
end
$migration$;
